# generated by datamodel-codegen:
#   filename:  generationform.json
#   timestamp: 2025-05-26T09:55:06+00:00

from __future__ import annotations
from pydantic import BaseModel


class GenerationForm(BaseModel):
    query: str


class SearchForm(BaseModel):
    query: str
    limit: int
