# generated by datamodel-codegen:
#   filename:  instance.json
#   timestamp: 2025-05-26T09:55:05+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Literal

from pydantic import BaseModel, Field

from .engines import MSSQL, MariaDB, Mongo, MySQL, Oracle, PostgreSQL, SQLite


class Type(str, Enum):
    LEAF = "leaf"
    ENUM = "enum"


class PrimitiveType(str, Enum):
    STRING = "string"
    INTEGER = "integer"
    FLOAT = "float"
    DATETIME = "datetime"
    DATE = "date"
    TIME = "time"
    BOOL = "bool"
    OID = "oid"
    UUID = "uuid"


class Variant(BaseModel):
    alias: str | None = None
    value: bool | int | float | str | None = None


class EnumField(BaseModel):
    alias: str | None = None
    description: str | None = None
    optional: bool | None = False
    type: Literal["enum"] = "enum"
    name: str
    variants: List[Variant]


class PrimitiveField(BaseModel):
    alias: str | None = None
    description: str | None = None
    optional: bool | None = False
    type: PrimitiveType


class Instance(BaseModel):
    description: str | None = None
    engine: Mongo | PostgreSQL | MySQL | MSSQL | Oracle | SQLite | MariaDB
    name: str
    tables: list[Table]


class ObjectField(BaseModel):
    alias: str | None = None
    description: str | None = None
    optional: bool | None = False
    properties: Dict[str, ObjectField | ArrayField | UnionField | EnumField | PrimitiveField]
    type: Literal["object"] = "object"


class ArrayField(BaseModel):
    alias: str | None = None
    description: str | None = None
    optional: bool | None = False
    item: ObjectField | ArrayField | UnionField | EnumField | PrimitiveField = Field(..., title="Field")
    type: Literal["array"] = "array"


class UnionField(BaseModel):
    alias: str | None = None
    description: str | None = None
    optional: bool | None = False
    types: List[ObjectField | ArrayField | UnionField | EnumField | PrimitiveField]
    type: Literal["union"] = "union"


class Table(BaseModel):
    name: str
    alias: str | None = None
    fields: Dict[str, ObjectField | ArrayField | UnionField | EnumField | PrimitiveField]


Instance.model_rebuild()
ObjectField.model_rebuild()
ArrayField.model_rebuild()
UnionField.model_rebuild()
