# generated by datamodel-codegen:
#   filename:  generationresponse.json
#   timestamp: 2025-05-26T09:55:06+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field
import uuid

from .engines import MSSQL, MariaDB, Mongo, MySQL, Oracle, PostgreSQL, SQLite, ClickHouse


class CacheInfo(BaseModel):
    usage: int
    was_cached: bool


class Assembled(BaseModel):
    query: Any
    target: Mongo | PostgreSQL | MySQL | MSSQL | Oracle | SQLite | MariaDB | ClickHouse


class OperationStats(BaseModel):
    operations_used: int
    operation_balance: int


class GenerationResponse(BaseModel):
    assembled: Assembled
    cache_info: CacheInfo
    pipeline_id: str
    operation_stats: OperationStats


class FoundPipeline(BaseModel):
    id: uuid.UUID = Field(..., alias="pipeline_id")
    query: str
    usage: int
    similarity: float


class SearchResponse(BaseModel):
    pipelines: list[FoundPipeline] = Field(..., alias="data")
